# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-523-tarfa/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx690tffg1761-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName work

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /data/et/myronm/wupper-interlaken/firmware/Projects/FLX709_INTERLAKEN/FLX709_INTERLAKEN.srcs/sources_1/ip/Transceiver_10g_64b67b
    /data/et/myronm/wupper-interlaken/firmware/Projects/FLX709_INTERLAKEN/FLX709_INTERLAKEN.srcs/sources_1/ip/clk_40MHz
  } {
      /eda/fpga/xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /eda/fpga/xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /eda/fpga/xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib work {
      ./.Xil/Vivado-523-tarfa/realtime/Transceiver_10g_64b67b_stub.vhdl
      ./.Xil/Vivado-523-tarfa/realtime/clk_40MHz_stub.vhdl
      /data/et/myronm/wupper-interlaken/firmware/sources/pcie/data_width_package_256.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/pcie/data_width_package_512.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/packages/pcie_package.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/packages/interlaken_package.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/axis_utils/axi_stream_package.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transceiver/transceiver_10g_64b67b_block_sync_sm.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/crc/crc-24.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transmitter/framing_burst.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/crc/crc-32.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transmitter/framing_meta.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transmitter/scrambler.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transmitter/encoder.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transmitter/interlaken_transmitter.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/axis_utils/axis64Fifo.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/transmitter/interlaken_transmitter_multiChannel.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/receiver/deframing_burst.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/receiver/deframing_meta.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/receiver/descrambler.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/receiver/decoder.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/receiver/interlaken_receiver.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/receiver/interlaken_receiver_multiChannel.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/interlaken/interface/interlaken_interface.vhd
      /data/et/myronm/wupper-interlaken/firmware/sources/application/application.vhd
    }
      rt::read_vhdl -lib xpm /eda/fpga/xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top application
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-523-tarfa/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
