-- Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity Transceiver_10g_64b67b is
  Port ( 
    SOFT_RESET_TX_IN : in STD_LOGIC;
    SOFT_RESET_RX_IN : in STD_LOGIC;
    DONT_RESET_ON_DATA_ERROR_IN : in STD_LOGIC;
    Q1_CLK0_GTREFCLK_PAD_N_IN : in STD_LOGIC;
    Q1_CLK0_GTREFCLK_PAD_P_IN : in STD_LOGIC;
    GT0_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT0_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT0_DATA_VALID_IN : in STD_LOGIC;
    GT0_TX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT0_RX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT1_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT1_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT1_DATA_VALID_IN : in STD_LOGIC;
    GT1_TX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT1_RX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT2_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT2_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT2_DATA_VALID_IN : in STD_LOGIC;
    GT2_TX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT2_RX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT3_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT3_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT3_DATA_VALID_IN : in STD_LOGIC;
    GT3_TX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT3_RX_MMCM_LOCK_OUT : out STD_LOGIC;
    GT0_TXUSRCLK_OUT : out STD_LOGIC;
    GT0_TXUSRCLK2_OUT : out STD_LOGIC;
    GT0_RXUSRCLK_OUT : out STD_LOGIC;
    GT0_RXUSRCLK2_OUT : out STD_LOGIC;
    GT1_TXUSRCLK_OUT : out STD_LOGIC;
    GT1_TXUSRCLK2_OUT : out STD_LOGIC;
    GT1_RXUSRCLK_OUT : out STD_LOGIC;
    GT1_RXUSRCLK2_OUT : out STD_LOGIC;
    GT2_TXUSRCLK_OUT : out STD_LOGIC;
    GT2_TXUSRCLK2_OUT : out STD_LOGIC;
    GT2_RXUSRCLK_OUT : out STD_LOGIC;
    GT2_RXUSRCLK2_OUT : out STD_LOGIC;
    GT3_TXUSRCLK_OUT : out STD_LOGIC;
    GT3_TXUSRCLK2_OUT : out STD_LOGIC;
    GT3_RXUSRCLK_OUT : out STD_LOGIC;
    GT3_RXUSRCLK2_OUT : out STD_LOGIC;
    gt0_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt0_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpen_in : in STD_LOGIC;
    gt0_drprdy_out : out STD_LOGIC;
    gt0_drpwe_in : in STD_LOGIC;
    gt0_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_eyescanreset_in : in STD_LOGIC;
    gt0_rxuserrdy_in : in STD_LOGIC;
    gt0_eyescandataerror_out : out STD_LOGIC;
    gt0_eyescantrigger_in : in STD_LOGIC;
    gt0_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt0_rxdata_out : out STD_LOGIC_VECTOR ( 63 downto 0 );
    gt0_gthrxn_in : in STD_LOGIC;
    gt0_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt0_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt0_rxoutclkfabric_out : out STD_LOGIC;
    gt0_rxdatavalid_out : out STD_LOGIC;
    gt0_rxheader_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_rxheadervalid_out : out STD_LOGIC;
    gt0_rxgearboxslip_in : in STD_LOGIC;
    gt0_gtrxreset_in : in STD_LOGIC;
    gt0_gthrxp_in : in STD_LOGIC;
    gt0_rxresetdone_out : out STD_LOGIC;
    gt0_gttxreset_in : in STD_LOGIC;
    gt0_txuserrdy_in : in STD_LOGIC;
    gt0_txheader_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_txdata_in : in STD_LOGIC_VECTOR ( 63 downto 0 );
    gt0_gthtxn_out : out STD_LOGIC;
    gt0_gthtxp_out : out STD_LOGIC;
    gt0_txoutclkfabric_out : out STD_LOGIC;
    gt0_txoutclkpcs_out : out STD_LOGIC;
    gt0_txsequence_in : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt0_txresetdone_out : out STD_LOGIC;
    gt1_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt1_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpen_in : in STD_LOGIC;
    gt1_drprdy_out : out STD_LOGIC;
    gt1_drpwe_in : in STD_LOGIC;
    gt1_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_eyescanreset_in : in STD_LOGIC;
    gt1_rxuserrdy_in : in STD_LOGIC;
    gt1_eyescandataerror_out : out STD_LOGIC;
    gt1_eyescantrigger_in : in STD_LOGIC;
    gt1_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt1_rxdata_out : out STD_LOGIC_VECTOR ( 63 downto 0 );
    gt1_gthrxn_in : in STD_LOGIC;
    gt1_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt1_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_rxoutclkfabric_out : out STD_LOGIC;
    gt1_rxdatavalid_out : out STD_LOGIC;
    gt1_rxheader_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_rxheadervalid_out : out STD_LOGIC;
    gt1_rxgearboxslip_in : in STD_LOGIC;
    gt1_gtrxreset_in : in STD_LOGIC;
    gt1_gthrxp_in : in STD_LOGIC;
    gt1_rxresetdone_out : out STD_LOGIC;
    gt1_gttxreset_in : in STD_LOGIC;
    gt1_txuserrdy_in : in STD_LOGIC;
    gt1_txheader_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_txdata_in : in STD_LOGIC_VECTOR ( 63 downto 0 );
    gt1_gthtxn_out : out STD_LOGIC;
    gt1_gthtxp_out : out STD_LOGIC;
    gt1_txoutclkfabric_out : out STD_LOGIC;
    gt1_txoutclkpcs_out : out STD_LOGIC;
    gt1_txsequence_in : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt1_txresetdone_out : out STD_LOGIC;
    gt2_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt2_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpen_in : in STD_LOGIC;
    gt2_drprdy_out : out STD_LOGIC;
    gt2_drpwe_in : in STD_LOGIC;
    gt2_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_eyescanreset_in : in STD_LOGIC;
    gt2_rxuserrdy_in : in STD_LOGIC;
    gt2_eyescandataerror_out : out STD_LOGIC;
    gt2_eyescantrigger_in : in STD_LOGIC;
    gt2_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt2_rxdata_out : out STD_LOGIC_VECTOR ( 63 downto 0 );
    gt2_gthrxn_in : in STD_LOGIC;
    gt2_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt2_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_rxoutclkfabric_out : out STD_LOGIC;
    gt2_rxdatavalid_out : out STD_LOGIC;
    gt2_rxheader_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_rxheadervalid_out : out STD_LOGIC;
    gt2_rxgearboxslip_in : in STD_LOGIC;
    gt2_gtrxreset_in : in STD_LOGIC;
    gt2_gthrxp_in : in STD_LOGIC;
    gt2_rxresetdone_out : out STD_LOGIC;
    gt2_gttxreset_in : in STD_LOGIC;
    gt2_txuserrdy_in : in STD_LOGIC;
    gt2_txheader_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_txdata_in : in STD_LOGIC_VECTOR ( 63 downto 0 );
    gt2_gthtxn_out : out STD_LOGIC;
    gt2_gthtxp_out : out STD_LOGIC;
    gt2_txoutclkfabric_out : out STD_LOGIC;
    gt2_txoutclkpcs_out : out STD_LOGIC;
    gt2_txsequence_in : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt2_txresetdone_out : out STD_LOGIC;
    gt3_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt3_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpen_in : in STD_LOGIC;
    gt3_drprdy_out : out STD_LOGIC;
    gt3_drpwe_in : in STD_LOGIC;
    gt3_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_eyescanreset_in : in STD_LOGIC;
    gt3_rxuserrdy_in : in STD_LOGIC;
    gt3_eyescandataerror_out : out STD_LOGIC;
    gt3_eyescantrigger_in : in STD_LOGIC;
    gt3_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt3_rxdata_out : out STD_LOGIC_VECTOR ( 63 downto 0 );
    gt3_gthrxn_in : in STD_LOGIC;
    gt3_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt3_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_rxoutclkfabric_out : out STD_LOGIC;
    gt3_rxdatavalid_out : out STD_LOGIC;
    gt3_rxheader_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_rxheadervalid_out : out STD_LOGIC;
    gt3_rxgearboxslip_in : in STD_LOGIC;
    gt3_gtrxreset_in : in STD_LOGIC;
    gt3_gthrxp_in : in STD_LOGIC;
    gt3_rxresetdone_out : out STD_LOGIC;
    gt3_gttxreset_in : in STD_LOGIC;
    gt3_txuserrdy_in : in STD_LOGIC;
    gt3_txheader_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_txdata_in : in STD_LOGIC_VECTOR ( 63 downto 0 );
    gt3_gthtxn_out : out STD_LOGIC;
    gt3_gthtxp_out : out STD_LOGIC;
    gt3_txoutclkfabric_out : out STD_LOGIC;
    gt3_txoutclkpcs_out : out STD_LOGIC;
    gt3_txsequence_in : in STD_LOGIC_VECTOR ( 6 downto 0 );
    gt3_txresetdone_out : out STD_LOGIC;
    GT0_QPLLLOCK_OUT : out STD_LOGIC;
    GT0_QPLLREFCLKLOST_OUT : out STD_LOGIC;
    GT0_QPLLOUTCLK_OUT : out STD_LOGIC;
    GT0_QPLLOUTREFCLK_OUT : out STD_LOGIC;
    sysclk_in : in STD_LOGIC
  );

end Transceiver_10g_64b67b;

architecture stub of Transceiver_10g_64b67b is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute x_core_info : string;
attribute x_core_info of stub : architecture is "Transceiver_10g_64b67b,gtwizard_v3_6_11,{protocol_file=Start_from_scratch}";
begin
end;
