# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz.xci
# IP: The module: 'clk_40MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz.xci
# IP: The module: 'clk_40MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
