# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/interlaken_0.xci
# IP: The module: 'interlaken_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/interlaken_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interlaken_0_gt || ORIG_REF_NAME==interlaken_0_gt} -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/synth/interlaken_0_gt_ooc.xdc

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/synth/interlaken_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interlaken_0_gt || ORIG_REF_NAME==interlaken_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'interlaken_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'interlaken_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interlaken_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/interlaken_0.xci
# IP: The module: 'interlaken_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/interlaken_0_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==interlaken_0_gt || ORIG_REF_NAME==interlaken_0_gt} -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/synth/interlaken_0_gt_ooc.xdc

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/synth/interlaken_0_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==interlaken_0_gt || ORIG_REF_NAME==interlaken_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'interlaken_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'interlaken_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'interlaken_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
