# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-7722-leover-Vostro-460/incrSyn
set_param power.BramSDPPropagationFix 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcvu9p-flgb2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.cache/wt [current_project]
set_property parent.project_path /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  /home/leover/Desktop/Core1990_Verification/sources/transmitter/framing_burst.vhd
  /home/leover/Desktop/Core1990_Verification/sources/transmitter/framing_meta.vhd
  /home/leover/Desktop/Core1990_Verification/sources/transmitter/scrambler.vhd
  /home/leover/Desktop/Core1990_Verification/sources/transmitter/encoder.vhd
  /home/leover/Desktop/Core1990_Verification/sources/transmitter/interlaken_transmitter.vhd
  /home/leover/Desktop/Core1990_Verification/sources/receiver/deframing_burst.vhd
  /home/leover/Desktop/Core1990_Verification/sources/receiver/deframing_meta.vhd
  /home/leover/Desktop/Core1990_Verification/sources/receiver/descrambler.vhd
  /home/leover/Desktop/Core1990_Verification/sources/receiver/decoder.vhd
  /home/leover/Desktop/Core1990_Verification/sources/receiver/interlaken_receiver.vhd
  /home/leover/Desktop/Core1990_Verification/sources/interlaken_interface.vhd
  /home/leover/Desktop/Core1990_Verification/sources/test/data_generator.vhd
  /home/leover/Desktop/Core1990_Verification/sources/crc/crc-24.vhd
  /home/leover/Desktop/Core1990_Verification/sources/crc/crc-32.vhd
  /home/leover/Desktop/Core1990_Verification/sources/test/Core1990_verification.vhd
}
read_ip -quiet /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/interlaken_0.xci
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/synth/interlaken_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/ip_0/synth/interlaken_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/interlaken_0/synth/interlaken_0_ooc.xdc]

read_ip -quiet /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO.xci
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO_ooc.xdc]

read_ip -quiet /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/TX_FIFO/TX_FIFO.xci
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/TX_FIFO/TX_FIFO.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/TX_FIFO/TX_FIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/TX_FIFO/TX_FIFO_ooc.xdc]

read_ip -quiet /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz.xci
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz_board.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz.xdc]
set_property used_in_implementation false [get_files -all /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/clk_40MHz/clk_40MHz_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/leover/Desktop/Core1990_Verification/constraints/Core1990_Constraints.xdc
set_property used_in_implementation false [get_files /home/leover/Desktop/Core1990_Verification/constraints/Core1990_Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Core199_verification -part xcvu9p-flgb2104-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Core199_verification.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Core199_verification_utilization_synth.rpt -pb Core199_verification_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
