set XCI_FILES ""
set VHDL_FILES ""
set VERILOG_FILES ""
set SIM_FILES ""
set EXCLUDE_SIM_FILES ""
set WCFG_FILES ""

set XCI_FILES_V7 ""
set VHDL_FILES_V7 ""
set SIM_FILES_V7 ""

set XCI_FILES_KU ""
set VHDL_FILES_KU ""
set SIM_FILES_KU ""

set XCI_FILES_VU9P ""
set VHDL_FILES_VU9P ""
set SIM_FILES_VU9P ""

set XCI_FILES_VU37P ""
set VHDL_FILES_VU37P ""
set SIM_FILES_VU37P ""

set XDC_FILES_VC709 ""
set XDC_FILES_HTG710 ""
set XDC_FILES_BNL711 ""
set XDC_FILES_BNL712 ""
set XDC_FILES_VCU128 ""
set XDC_FILES_XUPP3R_VU9P ""

