# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO.xci
# IP: The module: 'RX_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO.xci
# IP: The module: 'RX_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/leover/Desktop/Core1990_Verification/projects/core1990_interlaken_verification/core1990_interlaken_verification.srcs/sources_1/ip/RX_FIFO/RX_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RX_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
